### ISSUE TITLE
Logo Contribution

### ISSUE THREAD

**Issue by revilationer** [anordal/shellharden#13]
Hi
I just saw your app and if you need a new logo or widget design i can help you
You can tell me what kind of a logo do you want
I am waiting for you reply

**Comment by anordal** [comment]
LOL, I'm not a logo designer, so I wouldn't be offended if you made a nicer one, or just have some ideas. It doesn't have to be the same theme of course, but it needs to convey the core concept. I am pretty happy with the old logo because it does that.

I'm not sure what you mean by widget design. Make the program graphical? I don't expect that to be a concern for my target audience.

I'm not sure what else I could need, graphically. Maybe a mascot, but I'm not sure it is presentable to have both a logo and a mascot.

**Comment by xyproto** [comment]
I think the current logo is nice in that it's both "flat design" and has many elements that help in visually describing the project.

If there's a logo-competition going, here's my quick contribution:

![shellharden](https://i.imgur.com/zLNhmfr.png)

It has a hard shell too.

**Comment by anordal** [comment]
Now add the obligatory quoted dollar sign.

Maybe in a golden necklace. And while we're at it, add a cap, joint and pixelated sunglasses…

(don't take me too seriously)

**Comment by oxr463** [comment]
Yeah, the current logo needs love..

**Comment by xyproto** [comment]
Here's a new masterpiece for the logo competition:

![shellharden](https://user-images.githubusercontent.com/52813/75567082-3a964980-5a51-11ea-8f12-65c68028e925.png)

Have a good weekend!

**Comment by anordal** [comment]
Wow!

Nice incorporation of the obligatory quoted dollar. I like the cap too, the ninja-turtle-esque theme, and the ring around. A rust-gear would not be wrong either.

The joint was a joke (I've watched too much ThugLife), so don't take it as part of the kravspek. I can't really embrace smoking. I fell for the theme because it fits with dollars and bling.

Is he *doing* anything? There is room for more symbolism there. Or maybe it's just a mascot.
