### ISSUE TITLE
Request for Pacstall support

### ISSUE THREAD

**Issue by Elsie19** [anordal/shellharden#48]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing pull request to add [shellharden](https://github.com/pacstall/pacstall-programs/pull/783) to our repository.

We have a few questions for you:
* Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.
* Could you include a section in your documentation showing Pacstall as a valid method of installation for Shellharden for Debian/Ubuntu users? We could make a pull request for that if you want.

**Comment by anordal** [comment]
Thank you for your effort, Henry. You are more than welcome to package Shellharden!

Why the focus on Ubuntu, though?

* I would like to support at least OpenSuse as well, since that's what I use. The more, the merrier. As such, I think it makes more sense for me to concentrate on cross-distro packagers like [OBS](https://openbuildservice.org/), [Nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/shellharden/default.nix) or Guix. But thank you for the invitation.
* I used to have a little list of distro packages. Now, I link to [Repology](https://repology.org/project/shellharden/versions), which does a better job than me. Do you know if Repology knows about Pacstall packages yet? If not, I'll be happy to mention it.

**Comment by Elsie19** [comment]
The focus on Ubuntu is because packages in stable Ubuntu are usually outdated, and while that's kinda the point of Ubuntu (safe and stable), some people want a couple up to date packages (neovim comes to mind).

We are also working on Repology support in this [issue](https://github.com/repology/repology-updater/issues/1212).

---

We also have a FAQ [here](https://github.com/pacstall/pacstall/wiki/FAQ) if you want information.

**Comment by anordal** [comment]
Closing as completed. Thanks!

I see Repology has picked it up too:

[![Packaging status](https://camo.githubusercontent.com/05f1d44289f22059d5639eede0ac5988051c0b85513918ed03ecc932fff9231f/68747470733a2f2f7265706f6c6f67792e6f72672f62616467652f766572746963616c2d616c6c7265706f732f7368656c6c68617264656e2e737667)](https://repology.org/project/shellharden/versions)
