### ISSUE TITLE
{feat request] Binary releases

### ISSUE THREAD

**Issue by rbairwell** [anordal/shellharden#53]
Would it be possible to release just the built binary files (i.e. output of ../cargo/bin/shellharden ) for major platforms? It's just a pain to install gcc (55M), rust and cargo (254M) and all their associated stuff/dependencies, just to generate the 3.8M shellharden file which seems to run fine and dandy without any of the others (at least on Linux).

shellcheck seems to offer prebuilt binaries for linux.x86_86, linux.aarch64, linux.arm6hf, darwin.x86_64 and windows.x86_64 (as per https://github.com/koalaman/shellcheck/blob/master/.github/workflows/build.yml )

(I'm trying to build a reproducible Dockerfile for my own usage for bash development - at least at the moment - and I want it to be as small and lightweight as possible. I'm having to use the fixed .tar.gz installers of rust/cargo as I can't depend on rustup returning the same file every time)

**Comment by anordal** [comment]
See #51: I've just deleted my ~binary releases~ build artifacts. I built them (manually) on armhf and x86_64 for a while because I could at the time. It wasn't meant to be a commitment, but having an (incomplete) history of artifacts looked confusing on GitHub, because it makes people look at Releases instead of Tags.

Here are the runtime dependencies – just the platform specific obligatory libraries:

```
ldd (which shellharden)
        linux-vdso.so.1 (0x00007ffc053af000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fdd1ebc0000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fdd1e800000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdd1ee81000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fdd1ee1b000)
```

Tip: As long as you have those libraries, in those versions, you might as well just extract another distro's binary package. Such as this one (for the library versions above):
https://archlinux.org/packages/community/x86_64/shellharden/download

You shouldn't need gcc (there is no buildtime dependency on it), just libgcc. Minimal dockerfile:
https://github.com/anordal/shellharden/blob/5cad32d32465b22461e26786ebe00c6e4069d864/Dockerfile
